on: [push, pull_request]
name: YAML lint
jobs:
  Lint:
    name: Buluma YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Buluma YAML lint
        uses: ./
      - name: Create Issue
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Workflow failed for commit ${{github.sha}}
